# Generated by Django 6.0.5 on 2026-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='client_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка заказчика'),
        ),
        migrations.AddField(
            model_name='order',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Баллы за выполнение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_orders',
            field=models.IntegerField(default=0, verbose_name='Выполнено заказов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Всего баллов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_ratings',
            field=models.IntegerField(default=0, verbose_name='Всего оценок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('done', 'Выполнен'), ('rated', 'Оценен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
