# Generated by Django 6.0.5 on 2026-05-08 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Предложение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
