# Generated by Django 6.0.5 on 2026-05-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий админа'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('reviewed', 'Рассмотрено'), ('done', 'Выполнено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
