# Generated by Django 6.0.5 on 2026-05-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_suggestion_admin_comment_suggestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_hint',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль'),
        ),
    ]
